version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/.docker/config.json:/config.json
    command: --interval 10 --label-enable

  guessMyWiki:
    image: docker.pkg.github.com/clabroche/docker-registry/guessMyWiki:latest
    hostname: guessMyWiki
    restart: always
    environment:
      PORT: 9845
      mongoDbURL: mongodb://root:apasswordtochange@mongodb/guessMyWiki?authSource=admin
    labels:
      com.centurylinklabs.watchtower.enable: "true"

    expose:
      - 9845
    ports:
      - 9875:9845
    links:
      - mongodb
  mongodb:
    image: mongo:4
    hostname: mongodb
    restart: always
    expose:
      - 27017
    ports:
      - 2075:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: apasswordtochange
    command: mongod --port 27017
    volumes:
      - ./mongo-volume:/data/db
